### PR TITLE
Portfolio items icons

### PR DESCRIPTION
**Pull request by Hyperkid123**
### Changes
- added icons to portfolio items
- added icons to portfolio item detail
- added source icon to service if no icon is specified
  - for now it defaults to openshift icon but will be changing based on provider once we have more.
- added lazy loading to images to increase performance
  - network request for image will be fired only when the image is in view port

#### Lazy loading
lazy-loading

#### Item detail
screenshot-ci foo redhat com-1337-2019 04 05-11-01-32
#### Default icon if icon is missing
screenshot-ci foo redhat com-1337-2019 04 05-11-01-43

### CODE REVIEW

**Comment by gmcculloug** [comment]
cc @syncrou @lindgrenj6

**Comment by gmcculloug** [comment]
@Hyperkid123 This is deployed and looks great.  I think we just need one followup to update the icon and display name on the order dialog screen:

image

**Comment by Hyperkid123** [comment]
Yeah i agree. I would love to talk with Susan about the order modal a bit. Every time i open it i like it less and less :D.

**Comment by gmcculloug** [comment]
Sounds great, definitely talk to @sbuenafe-rh about it.  The initial delay while waiting for the dialog to generate could use some cosmetic help. 🙂 I'll try to get a screen grab of it, but it can be pretty quick some times.

**Pull request merged**
