### PR TITLE
Fix portfolio card link.

### PR DESCRIPTION
**Pull request by Hyperkid123**
Fixes missing link on portfolio card title.

portfolio-header

### CODE REVIEW

**Comment by Hyperkid123** [comment]
@sbuenafe-rh do we have some PF guideline on how to do these links in Cards?

**Comment by gmcculloug** [comment]
@Hyperkid123 @sbuenafe-rh Should (or even can) this feel more like the Product cards that do not change the title into a link?  Or change the Product card to have the title be a link so it is consistent.

Below is a screenshot of the Product card:

image

**Comment by sbuenafe-rh** [comment]
@Hyperkid123 Looks good!

**Comment by sbuenafe-rh** [comment]
@gmcculloug per our convo, Portfolio card title should be a link/clickable just as the Product card title behaves.

**Pull request merged**
