### PR TITLE
Hide vendor data when its empty in portfolio item detail.

### PR DESCRIPTION
**Pull request by Hyperkid123**
### Changes
- empty vendor name is now hidden

Before:
Screenshot from 2019-09-18 08-33-27

After:

Screenshot from 2019-09-18 08-32-21

### CODE REVIEW

**Comment by gmcculloug** [comment]
@Hyperkid123 Thanks, can you add before/after screenshots for this?

**Comment by lgalis** [comment]
@gmcculloug  - added screenshots - will merge the PR

**Comment by Hyperkid123** [comment]
> @Hyperkid123 Thanks, can you add before/after screenshots for this?

I was too slow

**Comment by gmcculloug** [comment]
That's what I thought it would look like.  😄   Thanks.

**Pull request merged**
