### PR TITLE
Empty states for platforms portfolios and portfolio screens

### PR DESCRIPTION
**Pull request by Hyperkid123**
### Changes
- added empty states for platforms portfolios and portfolio screens (not add/remove portfolio item screens)
- Icons is mostly subject to change but changing that is just a matter of importing different icon from PF.

All of them look similar just different text

screenshot-ci foo redhat com-1337-2019 04 11-16-43-35

### CODE REVIEW

**Comment by gmcculloug** [comment]
cc @sbuenafe-rh

**Comment by sbuenafe-rh** [comment]
@Hyperkid123 if no products exist in a portfolio, we should disable the "Remove products" button in the toolbar.

**Comment by martinpovolny** [comment]
@sbuenafe-rh:

> @Hyperkid123 if no products exist in a portfolio, we should disable the "Remove products" button in the toolbar.

Well yes, he is, obviously:
https://github.com/ManageIQ/catalog-ui/pull/153/files#diff-da61114cab5c53d2b1183ac5c81b3825R7

**Comment by martinpovolny** [comment]
> @Hyperkid123 if no products exist in a portfolio, we should disable the "Remove products" button in the toolbar.

@Hyperkid123 : please, address that in a follow up PR

**Pull request merged**
