### PR TITLE
Added time and UTC tool tip for order relative dates.

### PR DESCRIPTION
**Pull request by Hyperkid123**
### Changes
- Added time to date time to relative order dates.
- Added time to the date time column

fixes: #177 

Screenshot from 2019-04-30 14-00-34

cc @sbuenafe-rh

### CODE REVIEW

**Comment by Hyperkid123** [comment]
@sbuenafe-rh is this the correct visual change? I am kind of guessing with this. The tool tip is PF4 tool tip component.

**Comment by sbuenafe-rh** [comment]
@Hyperkid123 looks good, but you don't need the tooltip on the date/time because it's already precise date/time. 

as a side note, you will need the tooltip showing the precise date/tip over the relative times (ie Updated 2 days ago)

**Comment by Hyperkid123** [comment]
@sbuenafe-rh ok i am quire confused by the #177 conversation because the date is not standard UTC format (the in the tool tip is). Should i swap the format and remove the tool tip?

**Comment by sbuenafe-rh** [comment]
@Hyperkid123 you can take out the day "Thu" and the seconds from the time format and you'll be set for the tooltip.

**Comment by Hyperkid123** [comment]
Ok should be correct now. Thanks @sbuenafe-rh

**Pull request merged**
