### PR TITLE
Enabled editing of portfolio item attributes.

### PR DESCRIPTION
**Pull request by Hyperkid123**
### Changes
- added form to edit portfolio item attributes

edit-portfolio-item

### CODE REVIEW

**Comment by gmcculloug** [comment]
cc @sbuenafe-rh

**Comment by sbuenafe-rh** [comment]
@Hyperkid123 Looks good, should one of those fields be for the image uploader too?

**Comment by gmcculloug** [comment]
I would expect image uploader to be a separate PR.

**Comment by Hyperkid123** [comment]
@sbuenafe-rh i was thinking we will do the same pattern as GH does. When entering the edit page the will display some button/icon button which will serve as the uploader. What do you think about that?

**Comment by sbuenafe-rh** [comment]
@Hyperkid123 GH pattern works, but is it only available when you click on the Edit button under the kebab?

**Comment by Hyperkid123** [comment]
@sbuenafe-rh could be. That is your call probably.

**Comment by Hyperkid123** [comment]
@lgalis you are right! i will add the async select thanks.

**Comment by lgalis** [comment]
@Hyperkid123 - thank you, the async filtering is working well - but now there is no option to select 'None' if one wants to remove a workflow from a portfolio item.

**Comment by Hyperkid123** [comment]
:man_facepalming: I will add clear able prop

**Comment by sbuenafe-rh** [comment]
@Hyperkid123 for yah, for the edit icon, we'll have it display when a user clicks on the Edit button under the kebab dropdown. We can probably address this in the Image Uploader jira story. :)

**Comment by gmcculloug** [comment]
Is this PR ready for what it is doing?  Can image upload tasks be moved to a separate PR?

**Comment by sbuenafe-rh** [comment]
@gmcculloug yep image upload tasks can be moved as a separate PR

**Pull request merged**
